import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Container from "@mui/material/Container";

export const metadata: Metadata = {
  title: "Joke Fetcher!",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className="min-h-screen antialiased">
        <AppRouterCacheProvider>
          <Container>{children}</Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
